#!/usr/bin/env python3
import typer
import sys
import os
import subprocess

# Own libraries
from cli.vm import vm
from cli.host import host

""" Section below is responsible for the CLI input/output """
app = typer.Typer(context_settings=dict(max_content_width=800))
app.add_typer(vm.app, name="vm", help="List, Create, Remove and any do any other VM related operations")
app.add_typer(host.app, name="host", help="Show or modify the host related information")


# @app.command()
# def vmlist(json: bool = typer.Option(False, help="Output json instead of a table")):
#     """
#     Example: hoster vmlist
#     """

#     print("Hello this is VM List!")


# @app.command()
# def vmdeploy(quick: bool = typer.Option(True, help="Clone existing template ZFS dataset instead of copying over VM image")):
#     """
#     Example: hoster vmdeploy
#     """

#     print("Hello this is VM Deploy")



""" If this file is executed from the command line, activate Typer """
if __name__ == "__main__":
    app()